import concurrent.futures, json, subprocess
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
SYSTEM='High-end modern website design for ATLAS GROUP, a Michigan real estate, insurance, mortgage and construction company. Crisp flat UI screenshot, no device mockup. Palette true white #FFFFFF, ink navy #14263D, vivid blue #3268F5. Modern light-medium weight grotesk typography like Manrope. Airy asymmetrical editorial design, square-corner media, 64px outer gutters, fine horizontal rules. Simple outlined arrow icons. No gradients except neutral black readability fade over hero photo. No fake metrics, awards, testimonials, invented team members or fake listings. All text is readable and implementable in HTML/CSS. '
JOBS={
 'concept-hero':('gpt_image_2','16:9',SYSTEM+'Desktop first viewport 1440x810. White 88px header with small blue A emblem and navy uppercase ATLAS GROUP wordmark left; navigation Services, Our approach, About Atlas; blue button Let\u2019s talk at right. Below header full-width cinematic dusk photograph of a beautiful contemporary Michigan brick-and-wood home amid trees, warm windows, cobalt twilight, house mostly on right. Hero lower-left white large 84px headline exactly "Your next chapter. Built together." across three lines; below body "Real estate, insurance, mortgages, and construction. Connected around you." Main blue button "Find your next step" with diagonal arrow. Bottom-right tiny text "Rooted in Michigan. Looking forward." Minimal round pause button at far bottom-right. Hero has neutral black left-side readability gradient. Bottom of viewport shows a white four-column open service navigation strip with Real estate / Insurance / Mortgages / Construction and small arrows. No hero eyebrow or pretitle.'),
 'concept-services':('gpt_image_2','16:9',SYSTEM+'Standalone website service explorer section, no header or footer. White background. At top left small label OUR SERVICES with short blue horizontal dash; below big 58px headline "One relationship. More possibilities." Across two lines. At top right a short muted paragraph "A home. A plan. A new beginning. Wherever you are headed, start with a team that sees the bigger picture." Below: left 43% has four horizontal rows separated by fine rules, labeled 01 Real estate, 02 Insurance, 03 Mortgages, 04 Construction. First row expanded with muted text "Find your place. Make your move." and understated text link "Explore real estate" plus arrow; small bright blue active indicator. Right 57% is a large cinematic sunlit living room photograph with wood, brick, large windows, garden greenery. No nested cards, no bento, no icons other than simple arrows.'),
 'concept-approach':('gpt_image_2','16:9',SYSTEM+'Standalone website brand story and process section. Light cool-gray #F4F6F8 background. Left 46% large portrait photograph of a tree-lined Michigan neighborhood in warm afternoon light, traditional brick homes, contemporary renovations. Right 54% contains small OUR APPROACH label with blue dash, 54px heading "Forward thinking. Michigan grounded." and paragraph "Atlas brings property, protection, financing, and building into one conversation. Local experience. A clearer way forward." Under the paragraph are three numbered steps in open rows with subtle separators: 01 Start with your goals / Tell us what you have in mind.; 02 See the whole picture / Connect the right services and people.; 03 Move forward, together / Take the next step with a clear plan. At bottom right text link "Meet Atlas" and arrow. Sophisticated editorial spacing, no cards.'),
 'concept-contact':('gpt_image_2','16:9',SYSTEM+'Standalone last section and footer of website, total 900px high. Top 65% saturated brand blue #3268F5, white text. Left big heading "What does your next chapter look like?" 62px across 3 lines; small body "Tell us where you want to go. We will help you find the next step." Right minimalist embedded contact form on blue, white field surfaces with dark labels: name, email, service select, short message, white button "Start a conversation" with arrow. This is a form mockup, no fake successful message. Bottom 35% deep ink navy footer: white ATLAS GROUP wordmark on left and tagline "A clearer way forward." To right simple link columns SERVICES / Real estate / Insurance / Mortgages / Construction and ATLAS / Our approach / About us / Contact. Bottom fine line, Michigan \u00b7 Est. for what comes next omitted; actual bottom text "Metro Detroit. Serving Michigan." and Privacy, Accessibility. Very restrained editorial layout, no extra badges.'),
 'hero-home':('soul_location','16:9','Cinematic architectural editorial photograph for a modern Michigan real estate and financial services website. A beautifully renovated two-story modestly upscale Midwest home combining warm red-brown brick, natural oak cladding and black-framed windows, believable Metro Detroit neighborhood, mature maple trees, native grasses, warm golden indoor light at early blue hour. Wide landscape composition with the home predominantly in the right two thirds, left third darker garden and tree foliage with generous quiet negative space for a website headline. Ground-level camera from across the front lawn, 35mm lens, rich but natural color, exquisite realistic materials, atmospheric dusk sky, sophisticated architectural magazine photography. Contemporary and welcoming rather than a mansion or sterile luxury development. No text, no logos, no signs, no people, no cars, no watermarks.'),
 'interior':('soul_location','4:3','Cinematic architectural editorial photograph, a beautifully renovated attainable Michigan home living room. Warm oak flooring, off-white textured walls, retained exposed brick accent, large black-framed windows looking onto lush maple trees, soft beige linen sofa, low wood coffee table and one ceramic bowl, tasteful lived-in simplicity. Golden late-afternoon sunlight creates architectural shadows. Refined modern yet warm and approachable. Shot 35mm, realistic rich details, editorial magazine art direction, calm negative space, no text, no people, no logos.'),
 'neighborhood':('soul_location','3:4','Cinematic natural editorial photograph of a quiet walkable Metro Detroit residential street, early autumn afternoon. Beautiful ordinary Michigan red brick homes with front porches and a few sensitively renovated modern details, mature leafy trees arching over sidewalk, varied green landscaping, soft warm sunlight filtering through branches. Photographed from the sidewalk, rich organic textures, authentic midwestern place and community feel. No city skyline, no mansions, no visible people, no legible text, no logos, no signs. High-quality architectural film still with natural color and deep dimensional lighting.')
}
(ROOT/'design'/'asset-prompts.json').write_text(json.dumps(JOBS,indent=2))

def generate(item):
    name,(model,aspect,prompt)=item
    target=ROOT/'design'/f'{name}-job.json'
    if target.exists(): return name,'existing'
    cmd=['higgsfield','generate','create',model,'--prompt',prompt,'--aspect_ratio',aspect,'--wait','--wait-timeout','20m','--json']
    if model=='gpt_image_2': cmd+=['--resolution','2k']
    p=subprocess.run(cmd,capture_output=True,text=True)
    if p.returncode==0:
        target.write_text(p.stdout)
        return name,'complete'
    (ROOT/'design'/f'{name}-error.txt').write_text(p.stderr+'\n'+p.stdout)
    return name,'failed'

with concurrent.futures.ThreadPoolExecutor(max_workers=4) as pool:
    for result in pool.map(generate,JOBS.items()): print(*result,flush=True)
